### ISSUE TITLE
error on from bluepy.btle import ...

### ISSUE THREAD

**Issue by ghost** [amymcgovern/pymambo#1]
Hi,
I was testing your code (on a Raspberry Pi 1 Model A) and the installations run flawlessly.

But as I run the findMambo.py file, an error shows up in line 1 returning the unavailability of **bluepy.btle** that as far as I was able to trace, is another library.

Because no errors are return in the previous installations I assume that library should be somehow present. Am I'm missing a step or something?

(Incidentally the same error occurs in my Mac)

And thank you for releasing this code. My students are very happy about this.

**Comment by ghost** [comment]
Hi,

Ok, I figured out that blupy uses code from the bluez project and that's probably the culprit. I will focus on that.

Thanks.

**Comment by amymcgovern** [comment]
Right. I did say that you needed to install pybluez.  That is at the top of the README.  Did you install those?

**Comment by ghost** [comment]
All the command line instructions you provide on the README.

I'm wondering if the problem is with the Bluetooth chip itself. Pi 1 Model A doesn't have Bluetooth built-in, I must use a USB Bluetooth dongle. I will try to reproduce the installation in the same model as you.

Thanks.

**Comment by amymcgovern** [comment]
I bet that is it.  Remember that you need BLE support and not just bluetooth.  BLE is the low energy version.

**Comment by Djsurry** [comment]
when you run the file, make sure you run it from the command line with sudo. I had this same issue and simply going to directory your file is in and entering the following command fixed it:
sudo python yourFile.py

**Comment by Djsurry** [comment]
and make sure you use sudo when installing with pip. I have found my rpi is very sensitive when you do not use sudo
