### ISSUE TITLE
Drone Reconnecting bug

### ISSUE THREAD

**Issue by Djsurry** [amymcgovern/pymambo#3]
So I am working on a voice-activated drone. the general gist of my code is that I use my mac to access the google speech api for voice recognition, then i use flask and requests to send the commands over to my rpi which controls the drone. Connecting at first is fine, but then when I give the command to take-off, i get the following error messages:
reconnecting to wait
trying to re-connect to the mambo at address 'my addr'
retrying connections
trying to re-connect to the mambo at address 'my addr'
It keeps doing that so my command to take off doesn't work. Any help would be appreciated!

**Comment by amymcgovern** [comment]
Are you using BLE?  Or wifi?  If you are using wifi, I don't see how your network is working.  Presumably your Mac needs internet for voice and then you send to the RPI but the RPI needs to be on the mambo wifi to talk to it over wifi.

**Comment by amymcgovern** [comment]
And if you are using BLE, when you need a real address.  'my addr' isn't valid.  It needs to be a hex string found by findMambo.py

**Comment by amymcgovern** [comment]
Also, you need to be using the pyparrot package.  This one is no longer maintained. 
https://github.com/amymcgovern/pyparrot
