### ISSUE TITLE
Can it run on lemaker guitar?[Environmental problems]

### ISSUE THREAD

**Issue by 20gg** [amymcgovern/pymambo#4]
First I want it to run on lemaker, which has two python environments 2.7 and 3.4, the default python environment is python3.4;
so I command 
> sudo apt-get install bluetooth
But bluetooth is not installed.

could you tell me your system environment and software  environment ?
please

**Comment by amymcgovern** [comment]
Please look at the pyparrot package.  I am no longer maintaining pymambo.

https://github.com/amymcgovern/pyparrot

**Comment by 20gg** [comment]
thanks
